In [3]:
import numpy as np
import matplotlib.pyplot as plt



Criando vetores

In [4]:
vetor1 = np.array([1,2,3])
vetor2 = np.array([4,5,6])

print("Vetor 1:\n", vetor1)
print("Vetor 2:\n", vetor2)

Vetor 1:  [1 2 3]
Vetor 2:  [4 5 6]


In [7]:
vetor3 = np.array([[1], [2], [3]])
vetor4 = np.array([[4], [5], [6]])

print("Vetor 3:\n", vetor3)
print("Vetor 4:\n", vetor4)

Vetor 3:
 [[1]
 [2]
 [3]]
Vetor 4:
 [[4]
 [5]
 [6]]


Criando matrizes

In [9]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

print("Matriz 1:\n", matriz1)
print("Matriz 2:\n", matriz2)

Matriz 1:
 [[1 2]
 [3 4]]
Matriz 2:
 [[5 6]
 [7 8]]


Operações com matrizes

Adição: só ocorre em matrizes de mesma ordem

In [10]:
matriz_soma = matriz1 + matriz2
print("Matriz soma:\n", matriz_soma)

Matriz soma: 
 [[ 6  8]
 [10 12]]


Subtração: só ocorre em matriizes de mesma ordem

In [12]:
matriz_subtracao = matriz1 - matriz2
print("Matriz subtração:\n", matriz_subtracao)

Matriz subtração: 
 [[-4 -4]
 [-4 -4]]


Multiplicação de matrizes: multiplica a linha pela coluna

In [13]:
matriz_multiplicacao = np.dot(matriz1, matriz2)
print("Matriz multiplicação:\n", matriz_multiplicacao)

Matriz multiplicação: 
 [[19 22]
 [43 50]]


Matriz identidade: matriz quadrada, onde o valor da diagonal é o valor unitário (1)  e os demais elementos 0

In [14]:
matriz_identidade = np.eye(2)
print("Matriz identidade:\n", matriz_identidade)

Matriz identidade: 
 [[1. 0.]
 [0. 1.]]


Matriz transposta:

In [15]:
matriz_transposta = np.transpose(matriz1)
print("Matriz transposta:\n", matriz_transposta)

Matriz transposta: 
 [[1 3]
 [2 4]]


Números complexos

In [16]:
complexo1 = np.array([[1 + 2j, 3 + 4j], [5 + 6j, 7 + 8j]])
complexo2 = np.array([[1 - 2j, 3 - 4j], [5 - 6j, 7 - 8j]])

print("Complexos 1:\n", complexo1)
print("Complexo 2:\n", complexo2)

Complexos 1: 
 [[1.+2.j 3.+4.j]
 [5.+6.j 7.+8.j]]
Complexo 2: 
 [[1.-2.j 3.-4.j]
 [5.-6.j 7.-8.j]]


Matriz transposta conjugada (adjunta ou hermitiana): Transpoe a matriz e conjun ela, ao transpor mudamos de linha pra coluna e a o conjugar alteramos o sinal do conjugado

In [17]:
matriz_conjugada_transposta = np.conjugate(np.transpose(complexo1))

print("Matriz Transposta Conjugada:\n", matriz_conjugada_transposta)

Matriz Transposta Conjugada:
  [[1.-2.j 5.-6.j]
 [3.-4.j 7.-8.j]]


Traço da matriz: soma dos elementos da diagonal principal

In [19]:
traco_matriz1 = np.trace(matriz1)

print("Traço da matriz:\n", traco_matriz1)

Traço da matriz:
 5
