In [1]:
import numpy as np
import matplotlib.pyplot as plt

Definição do ket:
psi $|\psi\rangle$
phi $|\phi\rangle$

In [3]:
ket_psi = np.array([[1], [0]])
ket_phi = np.array([[0], [1]])

Exibindo com colchetes

In [5]:
print("ket_psi =\n", ket_psi)
print("ket_phi =\n", ket_phi)
print("")

ket_psi =
 [[1]
 [0]]
ket_phi =
 [[0]
 [1]]



Definição do bra: composto conjugado do ket

In [6]:
bra_psi = ket_psi.conj().T
bra_phi = ket_phi.conj().T

print("bra_psi:\n", bra_psi)
print("bra_phi:\n", bra_phi)

bra_psi:
 [[1 0]]
bra_phi:
 [[0 1]]


Produto interno (Bra-Ket)

In [8]:
inner_product = np.dot(bra_psi, ket_phi)
print("Produto Interno:\n", inner_product)

Produto Interno:
 [[0]]


Produto Externo (Ket-Bra)

In [9]:
outer_product = np.dot(ket_psi, bra_phi)
print("Produto Externo:\n", outer_product)

Produto Externo:
 [[0 1]
 [0 0]]


Produto Tensorial (Produto de Kroneker)

In [10]:
tensor_product = np.kron(ket_psi, ket_phi)
print("Produto Tensorial:\n", tensor_product)

Produto Tensorial:
 [[0]
 [1]
 [0]
 [0]]
